# -*- coding: utf-8 -*-
"""passwordreminder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nKUAmvE7GcNgwiZGjhgj6j390gcIoGM

Task : Let's say; you left a message in the past that prints a password you need. To see the password you wrote, you need to enter your name and the program should recognize you.
Write a program that 

Takes the first name from the user and compares it to yours,
Then if the name the user entered is the same as yours, print out such as : "Hello, Joseph! The password is : W@12",
If the name the user entered is not the same as yours, print out such as : "Hello, Amina! See you later."
"""

name = "Sezgin"
password = "Clarusway53"
inp_name = input("Please enter your name:").capitalize()

if inp_name == name :
  print(f"Hello {name}, your password is : {password}")
else:
  print(f"Hello {inp_name}, please enter the name correctly.")